
[font]
size = 18

[font.offset]
y = -1 # This negative y offset is relevant for the BlexMono Nerd Font

[font.bold]
family = "BlexMono Nerd Font"
# family = "hack nerd font"
# family = "BigBlueTerm437 Nerd Font"
# family = "3270 Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
# family = "hack nerd font"
# family = "BigBlueTerm437 Nerd Font"
# family = "3270 Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
# family = "hack nerd font"
# family = "BigBlueTerm437 Nerd Font"
# family = "3270 Nerd Font"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font"
# family = "hack nerd font"
# family = "BigBlueTerm437 Nerd Font"
# family = "3270 Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[terminal.shell]
program = "/opt/homebrew/bin/fish"

[window]
option_as_alt = "OnlyLeft"

[general]
live_config_reload = true
import = ["/Users/samuellock/.config/alacritty/color_light.toml"]

[terminal]
